version: "3.9"

networks:
  database:
    driver: bridge

services:
  lecturerservice:
    build: backend/LecturerService
    ports:
      - "4200:80"
    expose:
      - 1433
    depends_on:
      - sqlserver
    networks:
      - database

  sqlserver:
    hostname: sqlserver
    build: backend/SqlServer
    ports:
      - "1433:1433"
    expose:
      - 1433
    networks:
      - database