version: "3.9"

networks:
  database:
    driver: bridge

services:
  lecturerservice:
    build: backend/LecturerService
    depends_on:
      - sqlserver
    ############################
    #### Bridge network fix ####
    # 
    # If bridge network fails enable 'network_mode' 
    # and comment out 'ports' and 'networks'.
    # Also remove server entry in SqlServer ConnectionString in:
    # backend/LecturerService/appsettings.json
    #
    # This is development ONLY fix,
    # for production 'network_mode' should be commented out,
    # 'ports' and 'networks' should be enabled
    # and SqlServer Connection string should contain at the beginning:
    # Server=sqlserver;
    #
    ##### DEV ONLY FIX #####
    network_mode: host
    ##### PRODUCTION!! #####
    #ports:
    #  - "4200:80"
    #networks:
    # - database
    ############################

  sqlserver:
    hostname: sqlserver
    build: backend/SqlServer
    ports:
      - "1433:1433"
    expose:
      - 1433
    networks:
     - database