version: "3.9"

services:
  lecturerService:
    image: ${DOCKER_REGISTRY-}lecturer-service
    build: backend/LecturerService
    ports:
      - "4200:80"
    depends_on:
      - sqlserver

  sqlserver:
    image: sqlserver
    hostname: "sqlserver"
    build: backend/SqlServer
    expose:
      - 1433